controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

test_redis:
    path: /test-redis
    controller: App\Controller\TestRedisController::index

animal_select:
    path: /animal/select/{animalId}
    controller: App\Controller\AnimalController::selectAnimal
    methods: POST

animal_selection_count:
    path: /animal/selection-count/{animalId}
    controller: App\Controller\AnimalController::getSelectionCount
    methods: GET

animal_selection_counts:
    path : /animal/vues
    controller : App\Controller\AnimalController::getAllVues
    methods: GET
